// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTuiBZKcvsYZqXDSeiCeYyeRVG71XF3s',
    appId: '1:924318149939:android:8693a7f84da90dc422e246',
    messagingSenderId: '924318149939',
    projectId: 'nakaotalk-6cdd2',
    storageBucket: 'nakaotalk-6cdd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FKe_5e6KECOHqsqAoQbP1-XEPDcDtVo',
    appId: '1:924318149939:ios:0bb7e0fe2829b97822e246',
    messagingSenderId: '924318149939',
    projectId: 'nakaotalk-6cdd2',
    storageBucket: 'nakaotalk-6cdd2.appspot.com',
    androidClientId: '924318149939-gsm0ivvhvs1g1i1fuk7fqd8m2epa3i8f.apps.googleusercontent.com',
    iosClientId: '924318149939-v7qpe32na2upu9425r1slnkmrlbj0n62.apps.googleusercontent.com',
    iosBundleId: 'com.callor.hello',
  );
}
